.nh
.TH "fsserve" "1" "Apr 2023" "" ""

.SH NAME
.PP
fsserve - A file system http server


.SH SYNOPSIS
.PP
\fBfsserve [flags]\fP


.SH DESCRIPTION
.PP
A file system http server


.SH OPTIONS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/.fsserve.json)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for fsserve

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBfsserve-completion(1)\fP, \fBfsserve-doc(1)\fP, \fBfsserve-serve(1)\fP
