.nh
.TH "fsserve" "1" "Mar 2024" "" ""

.SH NAME
.PP
fsserve-tree-checksum - Checksums the content tree


.SH SYNOPSIS
.PP
\fBfsserve tree checksum [flags]\fP


.SH DESCRIPTION
.PP
Checksums the content tree


.SH OPTIONS
.PP
\fB--force\fP[=false]
	recomputes checksums for files with existing checksums

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for checksum


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is fsserve.json)

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB--log-plain\fP[=false]
	output plain text logs


.SH SEE ALSO
.PP
\fBfsserve-tree(1)\fP
