.nh
.TH "fsserve" "1" "Jul 2023" "" ""

.SH NAME
.PP
fsserve-doc - generate documentation for fsserve


.SH SYNOPSIS
.PP
\fBfsserve doc [flags]\fP


.SH DESCRIPTION
.PP
generate documentation for fsserve in several formats


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for doc

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is .fsserve.json)

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBfsserve(1)\fP, \fBfsserve-doc-man(1)\fP, \fBfsserve-doc-md(1)\fP
