.nh
.TH "fsserve" "1" "Jun 2023" "" ""

.SH NAME
.PP
fsserve-tree-init - Initializes the content tree db


.SH SYNOPSIS
.PP
\fBfsserve tree init [flags]\fP


.SH DESCRIPTION
.PP
Initializes the content tree db


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for init


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is .fsserve.json)

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBfsserve-tree(1)\fP
