.nh
.TH "fsserve" "1" "Mar 2024" "" ""

.SH NAME
.PP
fsserve-serve - Serves a local file system with an http server


.SH SYNOPSIS
.PP
\fBfsserve serve [flags]\fP


.SH DESCRIPTION
.PP
Serves a local file system with an http server


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for serve

.PP
\fB-p\fP, \fB--port\fP=0
	port to run the http server on (default 8080)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is .fsserve.json)

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB--log-plain\fP[=false]
	output plain text logs


.SH SEE ALSO
.PP
\fBfsserve(1)\fP
