.nh
.TH "fsserve" "1" "Dec 2023" "" ""

.SH NAME
.PP
fsserve-doc-man - Generate man page documentation for fsserve


.SH SYNOPSIS
.PP
\fBfsserve doc man [flags]\fP


.SH DESCRIPTION
.PP
Generate man page documentation for fsserve


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for man


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is .fsserve.json)

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB--log-plain\fP[=false]
	output plain text logs

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBfsserve-doc(1)\fP
