.nh
.TH "fsserve" "1" "Oct 2022" "" ""

.SH NAME
.PP
fsserve-doc-man - generate man page documentation for fsserve


.SH SYNOPSIS
.PP
\fBfsserve doc man [flags]\fP


.SH DESCRIPTION
.PP
generate man page documentation for fsserve


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for man


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/.fsserve.yaml)

.PP
\fB--debug\fP[=false]
	turn on debug output

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBfsserve-doc(1)\fP
