.nh
.TH "fsserve" "1" "Dec 2023" "" ""

.SH NAME
.PP
fsserve-tree-gc - GCs the content blob dir


.SH SYNOPSIS
.PP
\fBfsserve tree gc [flags]\fP


.SH DESCRIPTION
.PP
GCs the content blob dir


.SH OPTIONS
.PP
\fB--full\fP[=false]
	perform full gc

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for gc


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is .fsserve.json)

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB--log-plain\fP[=false]
	output plain text logs


.SH SEE ALSO
.PP
\fBfsserve-tree(1)\fP
