.nh
.TH "fsserve" "1" "Dec 2023" "" ""

.SH NAME
.PP
fsserve-tree - Manages the server content tree


.SH SYNOPSIS
.PP
\fBfsserve tree [flags]\fP


.SH DESCRIPTION
.PP
Manages the server content tree


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for tree


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is .fsserve.json)

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB--log-plain\fP[=false]
	output plain text logs


.SH SEE ALSO
.PP
\fBfsserve(1)\fP, \fBfsserve-tree-add(1)\fP, \fBfsserve-tree-gc(1)\fP, \fBfsserve-tree-init(1)\fP, \fBfsserve-tree-rm(1)\fP, \fBfsserve-tree-sync(1)\fP
