.nh
.TH "fsserve" "1" "Dec 2023" "" ""

.SH NAME
.PP
fsserve-tree-add - Adds a content blob and updates the tree


.SH SYNOPSIS
.PP
\fBfsserve tree add [flags]\fP


.SH DESCRIPTION
.PP
Adds a content blob and updates the tree


.SH OPTIONS
.PP
\fB--contenttype\fP=""
	content type of src

.PP
\fB-e\fP, \fB--enc\fP=[]
	encoded versions of the file in the form of (code:filename)

.PP
\fB-f\fP, \fB--file\fP=""
	destination filepath

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for add

.PP
\fB-s\fP, \fB--src\fP=""
	file to add


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-b\fP, \fB--base\fP=""
	static files base

.PP
\fB--config\fP=""
	config file (default is .fsserve.json)

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB--log-plain\fP[=false]
	output plain text logs


.SH SEE ALSO
.PP
\fBfsserve-tree(1)\fP
